// <auto-generated />
using System;
using BackEnd.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BackEnd.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250531022751_MakeSuggestionTipsNullableInEntity")]
    partial class MakeSuggestionTipsNullableInEntity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.4");

            modelBuilder.Entity("BackEnd.Models.MaterialRecyclingGuide", b =>
                {
                    b.Property<string>("MaterialNameKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayMaterialName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DisposalTips")
                        .HasColumnType("TEXT");

                    b.Property<string>("RecyclingInfo")
                        .HasColumnType("TEXT");

                    b.Property<string>("SustainabilityImpact")
                        .HasColumnType("TEXT");

                    b.HasKey("MaterialNameKey");

                    b.ToTable("MaterialRecyclingGuides");

                    b.HasData(
                        new
                        {
                            MaterialNameKey = "Plástico",
                            DisplayMaterialName = "Plástico",
                            DisposalTips = "Lave, seque e, se possível, amasse embalagens plásticas. Verifique o símbolo de reciclabilidade (ex: PET, PP).",
                            RecyclingInfo = "Muitos plásticos são recicláveis. Evite misturar com orgânicos. Isopor e embalagens metalizadas geralmente não são.",
                            SustainabilityImpact = "Reciclar plástico economiza petróleo e energia, reduzindo o lixo em aterros."
                        },
                        new
                        {
                            MaterialNameKey = "Vidro",
                            DisplayMaterialName = "Vidro",
                            DisposalTips = "Lave potes e garrafas. Deposite em coletores verdes. Embale vidros quebrados com segurança e sinalize.",
                            RecyclingInfo = "Vidro é 100% reciclável. Não misture com cerâmica, espelhos ou lâmpadas.",
                            SustainabilityImpact = "Economia infinita de matéria-prima e energia na reciclagem."
                        },
                        new
                        {
                            MaterialNameKey = "Papel",
                            DisplayMaterialName = "Papel",
                            DisposalTips = "Mantenha seco e limpo. Não amasse em bola. Remova clipes grandes.",
                            RecyclingInfo = "Jornais, revistas, folhas são recicláveis. Papel carbono, fotográfico ou plastificado não são.",
                            SustainabilityImpact = "Salva árvores, água e energia."
                        },
                        new
                        {
                            MaterialNameKey = "Papelão",
                            DisplayMaterialName = "Papelão",
                            DisposalTips = "Desmonte caixas. Mantenha seco e limpo. Embalagens longa vida podem ter coleta específica.",
                            RecyclingInfo = "Papelão limpo é reciclável. Evite o que estiver muito engordurado.",
                            SustainabilityImpact = "Conserva recursos e reduz o volume de lixo."
                        },
                        new
                        {
                            MaterialNameKey = "Metal",
                            DisplayMaterialName = "Metal (Aço/Ferro)",
                            DisposalTips = "Latas de alimentos (aço), tampas. Lave e amasse, se possível.",
                            RecyclingInfo = "Metais ferrosos são recicláveis. Não misture com pilhas ou latas de tinta/químicos.",
                            SustainabilityImpact = "Reduz a extração de minério e o consumo de energia."
                        },
                        new
                        {
                            MaterialNameKey = "Alumínio",
                            DisplayMaterialName = "Alumínio",
                            DisposalTips = "Latas de bebidas, papel alumínio limpo. Lave e amasse.",
                            RecyclingInfo = "Altamente reciclável, economizando até 95% de energia.",
                            SustainabilityImpact = "Diminui a necessidade de mineração de bauxita."
                        },
                        new
                        {
                            MaterialNameKey = "Borracha",
                            DisplayMaterialName = "Borracha",
                            DisposalTips = "Pneus velhos geralmente têm pontos de coleta específicos ou ecopontos. Outros itens de borracha, verifique localmente.",
                            RecyclingInfo = "A reciclagem de borracha é complexa, mas possível para certos tipos, transformando-a em outros produtos.",
                            SustainabilityImpact = "Evita o descarte inadequado e pode gerar novos materiais."
                        },
                        new
                        {
                            MaterialNameKey = "Orgânico",
                            DisplayMaterialName = "Resíduo Orgânico",
                            DisposalTips = "Restos de frutas, verduras, legumes, cascas de ovos, borra de café. Pode ser usado em compostagem doméstica.",
                            RecyclingInfo = "Não misture com lixo reciclável ou rejeitos. Evite carnes, laticínios e gorduras na compostagem caseira (a menos que tenha um sistema adequado).",
                            SustainabilityImpact = "Reduz o metano em aterros e produz adubo rico para o solo."
                        },
                        new
                        {
                            MaterialNameKey = "Eletrônico",
                            DisplayMaterialName = "Lixo Eletrônico",
                            DisposalTips = "Celulares, computadores, pilhas, baterias, TVs. NUNCA descarte no lixo comum ou reciclável.",
                            RecyclingInfo = "Procure pontos de coleta específicos para lixo eletrônico (lojas, fabricantes, ecopontos municipais). Contêm metais pesados e substâncias tóxicas.",
                            SustainabilityImpact = "O descarte correto evita contaminação do solo/água e permite a recuperação de materiais valiosos."
                        },
                        new
                        {
                            MaterialNameKey = "en:plastic",
                            DisplayMaterialName = "Plástico (API)",
                            DisposalTips = "Lave, seque e, se possível, amasse embalagens como garrafas PET, embalagens de produtos de limpeza/higiene e potes de alimentos. Verifique o símbolo de reciclabilidade.",
                            RecyclingInfo = "Geralmente não são recicláveis (verifique na sua cidade): isopor, embalagens metalizadas (ex: salgadinhos), adesivos e plásticos termorrígidos. Estes devem ir para o lixo comum para não contaminar o processo.",
                            SustainabilityImpact = "Reciclar plástico economiza recursos naturais (petróleo), energia e reduz o volume de lixo nos aterros."
                        },
                        new
                        {
                            MaterialNameKey = "en:aluminium",
                            DisplayMaterialName = "Alumínio (API)",
                            DisposalTips = "Latas de alumínio e aço (bebidas, alimentos), tampas metálicas e papel alumínio devem estar limpos. Latas preferencialmente amassadas.",
                            RecyclingInfo = "Não devem ser misturados aos recicláveis comuns: esponjas de aço, latas de tinta ou produtos químicos. Pilhas e baterias exigem descarte especial em pontos de coleta específicos.",
                            SustainabilityImpact = "Reciclar metais, especialmente alumínio, economiza uma quantidade significativa de energia e reduz a necessidade de mineração."
                        },
                        new
                        {
                            MaterialNameKey = "en:glass",
                            DisplayMaterialName = "Vidro (API)",
                            DisposalTips = "Garrafas, potes e frascos devem ser descartados limpos. Cacos de vidro precisam ser cuidadosamente embalados em jornal ou caixa de papelão resistente e devidamente sinalizados com 'CUIDADO: VIDRO QUEBRADO'.",
                            RecyclingInfo = "Não são recicláveis: espelhos, vidros temperados (Pyrex, box de banheiro), lâmpadas (requerem descarte especial), cerâmicas ou porcelanas. Estes devem ir para o lixo comum ou pontos de coleta específicos.",
                            SustainabilityImpact = "O vidro é 100% reciclável e pode ser reciclado infinitas vezes, economizando energia e matéria-prima."
                        },
                        new
                        {
                            MaterialNameKey = "en:paper",
                            DisplayMaterialName = "Papel (API)",
                            DisposalTips = "Descarte jornais, revistas, folhas de caderno e caixas de papel limpas e secas. Evite amassar em bola. Remova contaminantes como clipes grandes ou fitas adesivas.",
                            RecyclingInfo = "Não são recicláveis: papéis higiênicos usados, papel carbono, fotografias, papéis plastificados ou aqueles muito sujos com gordura ou restos de alimentos (estes vão para o lixo comum).",
                            SustainabilityImpact = "Reciclar papel salva árvores, reduz o consumo de água e energia, e diminui a quantidade de resíduos em aterros."
                        },
                        new
                        {
                            MaterialNameKey = "en:cardboard",
                            DisplayMaterialName = "Papelão (API)",
                            DisposalTips = "Desmonte caixas para reduzir volume. Certifique-se de que estejam limpas, livres de gordura ou umidade excessiva. Embalagens longa vida (Tetra Pak) podem ser recicladas se sua cidade tiver coleta específica.",
                            RecyclingInfo = "Não são recicláveis: Papelão muito engordurado (como o fundo de caixas de pizza sujas) ou molhado (estes vão para o lixo comum).",
                            SustainabilityImpact = "A reciclagem de papelão conserva recursos naturais, economiza energia e reduz o lixo em aterros."
                        });
                });

            modelBuilder.Entity("BackEnd.Models.Product", b =>
                {
                    b.Property<string>("Barcode")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisposalTips")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("TEXT");

                    b.Property<string>("Material")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RecyclingInfo")
                        .HasColumnType("TEXT");

                    b.Property<string>("SustainabilityImpact")
                        .HasColumnType("TEXT");

                    b.HasKey("Barcode");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Barcode = "7891000315507",
                            DateAdded = new DateTime(2025, 5, 31, 2, 27, 50, 340, DateTimeKind.Utc).AddTicks(3392),
                            DisposalTips = "Lave e amasse a lata. Deposite no cesto amarelo.",
                            LastUpdated = new DateTime(2025, 5, 31, 2, 27, 50, 340, DateTimeKind.Utc).AddTicks(3395),
                            Material = "Alumínio",
                            ProductName = "Refrigerante em Lata",
                            RecyclingInfo = "O alumínio é 100% reciclável. Reciclar economiza 95% da energia.",
                            SustainabilityImpact = "Reduz a extração de bauxita e o consumo de energia."
                        },
                        new
                        {
                            Barcode = "7891991010769",
                            DateAdded = new DateTime(2025, 5, 31, 2, 27, 50, 340, DateTimeKind.Utc).AddTicks(3399),
                            DisposalTips = "Esvazie, lave e amasse a garrafa. Separe a tampa. Deposite no cesto vermelho.",
                            LastUpdated = new DateTime(2025, 5, 31, 2, 27, 50, 340, DateTimeKind.Utc).AddTicks(3400),
                            Material = "Plástico PET",
                            ProductName = "Água Mineral Garrafa PET",
                            RecyclingInfo = "PET é reciclável. A tampa (PP/PEAD) também. O rótulo pode precisar ser removido.",
                            SustainabilityImpact = "Reduz extração de petróleo e volume em aterros."
                        },
                        new
                        {
                            Barcode = "7896005800057",
                            DateAdded = new DateTime(2025, 5, 31, 2, 27, 50, 340, DateTimeKind.Utc).AddTicks(3403),
                            DisposalTips = "Esvazie e amasse levemente. Algumas cidades coletam separadamente.",
                            LastUpdated = new DateTime(2025, 5, 31, 2, 27, 50, 340, DateTimeKind.Utc).AddTicks(3404),
                            Material = "Embalagem Cartonada (Papelão, Plástico, Alumínio)",
                            ProductName = "Leite Longa Vida Caixa",
                            RecyclingInfo = "A reciclagem de embalagens longa vida é possível, mas depende da infraestrutura local.",
                            SustainabilityImpact = "Quando reciclada, contribui para a economia de recursos."
                        },
                        new
                        {
                            Barcode = "7891149101017",
                            DateAdded = new DateTime(2025, 5, 31, 2, 27, 50, 340, DateTimeKind.Utc).AddTicks(3407),
                            DisposalTips = "Lave a garrafa. Deposite no cesto verde. Cuidado com cacos.",
                            LastUpdated = new DateTime(2025, 5, 31, 2, 27, 50, 340, DateTimeKind.Utc).AddTicks(3408),
                            Material = "Vidro",
                            ProductName = "Cerveja Garrafa de Vidro",
                            RecyclingInfo = "Vidro é 100% reciclável.",
                            SustainabilityImpact = "Economia de energia e matéria-prima."
                        },
                        new
                        {
                            Barcode = "1234567890000",
                            DateAdded = new DateTime(2025, 5, 31, 2, 27, 50, 340, DateTimeKind.Utc).AddTicks(3411),
                            DisposalTips = "Remova a espiral metálica se possível (descarte com metais). As folhas de papel limpas vão para o cesto azul.",
                            LastUpdated = new DateTime(2025, 5, 31, 2, 27, 50, 340, DateTimeKind.Utc).AddTicks(3411),
                            Material = "Papel e Metal (espiral)",
                            ProductName = "Caderno Espiral",
                            RecyclingInfo = "Folhas de papel são recicláveis. A espiral metálica também.",
                            SustainabilityImpact = "Contribui para a preservação de árvores."
                        });
                });

            modelBuilder.Entity("BackEnd.Models.Suggestion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Barcode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateSubmitted")
                        .HasColumnType("TEXT");

                    b.Property<string>("Material")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Barcode");

                    b.ToTable("Suggestions");
                });
#pragma warning restore 612, 618
        }
    }
}
