// <auto-generated />
using System;
using BackEnd.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BackEnd.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.4");

            modelBuilder.Entity("BackEnd.Models.MaterialRecyclingGuide", b =>
                {
                    b.Property<string>("MaterialNameKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayMaterialName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DisposalTips")
                        .HasColumnType("TEXT");

                    b.Property<string>("RecyclingInfo")
                        .HasColumnType("TEXT");

                    b.Property<string>("SustainabilityImpact")
                        .HasColumnType("TEXT");

                    b.HasKey("MaterialNameKey");

                    b.ToTable("MaterialRecyclingGuides");

                    b.HasData(
                        new
                        {
                            MaterialNameKey = "papel",
                            DisplayMaterialName = "Papel",
                            DisposalTips = "Descarte jornais, revistas, folhas de caderno e caixas de papel limpas e secas. Evite amassar em bola. Remova contaminantes como clipes grandes ou fitas adesivas.",
                            RecyclingInfo = "Não são recicláveis: papéis higiênicos usados, papel carbono, fotografias, papéis plastificados ou aqueles muito sujos com gordura ou restos de alimentos (estes vão para o lixo comum).",
                            SustainabilityImpact = "Reciclar papel salva árvores, reduz o consumo de água e energia, e diminui a quantidade de resíduos em aterros."
                        },
                        new
                        {
                            MaterialNameKey = "papelao",
                            DisplayMaterialName = "Papelão",
                            DisposalTips = "Desmonte caixas para reduzir volume. Certifique-se de que estejam limpas, livres de gordura ou umidade excessiva. Embalagens longa vida (Tetra Pak) podem ser recicladas se sua cidade tiver coleta específica.",
                            RecyclingInfo = "Não são recicláveis: Papelão muito engordurado (como o fundo de caixas de pizza sujas) ou molhado (estes vão para o lixo comum).",
                            SustainabilityImpact = "A reciclagem de papelão conserva recursos naturais, economiza energia e reduz o lixo em aterros."
                        },
                        new
                        {
                            MaterialNameKey = "plastico",
                            DisplayMaterialName = "Plásticos",
                            DisposalTips = "Lave, seque e, se possível, amasse embalagens como garrafas PET, embalagens de produtos de limpeza/higiene e potes de alimentos. Verifique o símbolo de reciclabilidade.",
                            RecyclingInfo = "Geralmente não são recicláveis (verifique na sua cidade): isopor, embalagens metalizadas (ex: salgadinhos), adesivos e plásticos termorrígidos. Estes devem ir para o lixo comum para não contaminar o processo.",
                            SustainabilityImpact = "Reciclar plástico economiza recursos naturais (petróleo), energia e reduz o volume de lixo nos aterros."
                        },
                        new
                        {
                            MaterialNameKey = "metal",
                            DisplayMaterialName = "Metais",
                            DisposalTips = "Latas de alumínio e aço (bebidas, alimentos), tampas metálicas e papel alumínio devem estar limpos. Latas preferencialmente amassadas.",
                            RecyclingInfo = "Não devem ser misturados aos recicláveis comuns: esponjas de aço, latas de tinta ou produtos químicos. Pilhas e baterias exigem descarte especial em pontos de coleta específicos.",
                            SustainabilityImpact = "Reciclar metais, especialmente alumínio, economiza uma quantidade significativa de energia e reduz a necessidade de mineração."
                        },
                        new
                        {
                            MaterialNameKey = "vidro",
                            DisplayMaterialName = "Vidro",
                            DisposalTips = "Garrafas, potes e frascos devem ser descartados limpos. Cacos de vidro precisam ser cuidadosamente embalados em jornal ou caixa de papelão resistente e devidamente sinalizados com 'CUIDADO: VIDRO QUEBRADO'.",
                            RecyclingInfo = "Não são recicláveis: espelhos, vidros temperados (Pyrex, box de banheiro), lâmpadas (requerem descarte especial), cerâmicas ou porcelanas. Estes devem ir para o lixo comum ou pontos de coleta específicos.",
                            SustainabilityImpact = "O vidro é 100% reciclável e pode ser reciclado infinitas vezes, economizando energia e matéria-prima."
                        },
                        new
                        {
                            MaterialNameKey = "en:plastic",
                            DisplayMaterialName = "Plástico (API)",
                            DisposalTips = "Lave, seque e, se possível, amasse embalagens como garrafas PET, embalagens de produtos de limpeza/higiene e potes de alimentos. Verifique o símbolo de reciclabilidade.",
                            RecyclingInfo = "Geralmente não são recicláveis (verifique na sua cidade): isopor, embalagens metalizadas (ex: salgadinhos), adesivos e plásticos termorrígidos. Estes devem ir para o lixo comum para não contaminar o processo.",
                            SustainabilityImpact = "Reciclar plástico economiza recursos naturais (petróleo), energia e reduz o volume de lixo nos aterros."
                        },
                        new
                        {
                            MaterialNameKey = "en:aluminium",
                            DisplayMaterialName = "Alumínio (API)",
                            DisposalTips = "Latas de alumínio e aço (bebidas, alimentos), tampas metálicas e papel alumínio devem estar limpos. Latas preferencialmente amassadas.",
                            RecyclingInfo = "Não devem ser misturados aos recicláveis comuns: esponjas de aço, latas de tinta ou produtos químicos. Pilhas e baterias exigem descarte especial em pontos de coleta específicos.",
                            SustainabilityImpact = "Reciclar metais, especialmente alumínio, economiza uma quantidade significativa de energia e reduz a necessidade de mineração."
                        },
                        new
                        {
                            MaterialNameKey = "en:glass",
                            DisplayMaterialName = "Vidro (API)",
                            DisposalTips = "Garrafas, potes e frascos devem ser descartados limpos. Cacos de vidro precisam ser cuidadosamente embalados em jornal ou caixa de papelão resistente e devidamente sinalizados com 'CUIDADO: VIDRO QUEBRADO'.",
                            RecyclingInfo = "Não são recicláveis: espelhos, vidros temperados (Pyrex, box de banheiro), lâmpadas (requerem descarte especial), cerâmicas ou porcelanas. Estes devem ir para o lixo comum ou pontos de coleta específicos.",
                            SustainabilityImpact = "O vidro é 100% reciclável e pode ser reciclado infinitas vezes, economizando energia e matéria-prima."
                        },
                        new
                        {
                            MaterialNameKey = "en:paper",
                            DisplayMaterialName = "Papel (API)",
                            DisposalTips = "Descarte jornais, revistas, folhas de caderno e caixas de papel limpas e secas. Evite amassar em bola. Remova contaminantes como clipes grandes ou fitas adesivas.",
                            RecyclingInfo = "Não são recicláveis: papéis higiênicos usados, papel carbono, fotografias, papéis plastificados ou aqueles muito sujos com gordura ou restos de alimentos (estes vão para o lixo comum).",
                            SustainabilityImpact = "Reciclar papel salva árvores, reduz o consumo de água e energia, e diminui a quantidade de resíduos em aterros."
                        },
                        new
                        {
                            MaterialNameKey = "en:cardboard",
                            DisplayMaterialName = "Papelão (API)",
                            DisposalTips = "Desmonte caixas para reduzir volume. Certifique-se de que estejam limpas, livres de gordura ou umidade excessiva. Embalagens longa vida (Tetra Pak) podem ser recicladas se sua cidade tiver coleta específica.",
                            RecyclingInfo = "Não são recicláveis: Papelão muito engordurado (como o fundo de caixas de pizza sujas) ou molhado (estes vão para o lixo comum).",
                            SustainabilityImpact = "A reciclagem de papelão conserva recursos naturais, economiza energia e reduz o lixo em aterros."
                        });
                });

            modelBuilder.Entity("BackEnd.Models.Product", b =>
                {
                    b.Property<string>("Barcode")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisposalTips")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("TEXT");

                    b.Property<string>("Material")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RecyclingInfo")
                        .HasColumnType("TEXT");

                    b.Property<string>("SustainabilityImpact")
                        .HasColumnType("TEXT");

                    b.HasKey("Barcode");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Barcode = "7891000315507",
                            DateAdded = new DateTime(2025, 5, 30, 5, 11, 21, 913, DateTimeKind.Utc).AddTicks(5240),
                            DisposalTips = "Lave e amasse a lata. Deposite no cesto amarelo.",
                            LastUpdated = new DateTime(2025, 5, 30, 5, 11, 21, 913, DateTimeKind.Utc).AddTicks(5285),
                            Material = "Alumínio",
                            ProductName = "Refrigerante em Lata",
                            RecyclingInfo = "O alumínio é 100% reciclável. Reciclar economiza 95% da energia.",
                            SustainabilityImpact = "Reduz a extração de bauxita e o consumo de energia."
                        },
                        new
                        {
                            Barcode = "7891991010769",
                            DateAdded = new DateTime(2025, 5, 30, 5, 11, 21, 913, DateTimeKind.Utc).AddTicks(5291),
                            DisposalTips = "Esvazie, lave e amasse a garrafa. Separe a tampa. Deposite no cesto vermelho.",
                            LastUpdated = new DateTime(2025, 5, 30, 5, 11, 21, 913, DateTimeKind.Utc).AddTicks(5293),
                            Material = "Plástico PET",
                            ProductName = "Água Mineral Garrafa PET",
                            RecyclingInfo = "PET é reciclável. A tampa (PP/PEAD) também. O rótulo pode precisar ser removido.",
                            SustainabilityImpact = "Reduz extração de petróleo e volume em aterros."
                        },
                        new
                        {
                            Barcode = "7896005800057",
                            DateAdded = new DateTime(2025, 5, 30, 5, 11, 21, 913, DateTimeKind.Utc).AddTicks(5298),
                            DisposalTips = "Esvazie e amasse levemente. Algumas cidades coletam separadamente.",
                            LastUpdated = new DateTime(2025, 5, 30, 5, 11, 21, 913, DateTimeKind.Utc).AddTicks(5299),
                            Material = "Embalagem Cartonada (Papelão, Plástico, Alumínio)",
                            ProductName = "Leite Longa Vida Caixa",
                            RecyclingInfo = "A reciclagem de embalagens longa vida é possível, mas depende da infraestrutura local.",
                            SustainabilityImpact = "Quando reciclada, contribui para a economia de recursos."
                        },
                        new
                        {
                            Barcode = "7891149101017",
                            DateAdded = new DateTime(2025, 5, 30, 5, 11, 21, 913, DateTimeKind.Utc).AddTicks(5304),
                            DisposalTips = "Lave a garrafa. Deposite no cesto verde. Cuidado com cacos.",
                            LastUpdated = new DateTime(2025, 5, 30, 5, 11, 21, 913, DateTimeKind.Utc).AddTicks(5305),
                            Material = "Vidro",
                            ProductName = "Cerveja Garrafa de Vidro",
                            RecyclingInfo = "Vidro é 100% reciclável.",
                            SustainabilityImpact = "Economia de energia e matéria-prima."
                        },
                        new
                        {
                            Barcode = "1234567890000",
                            DateAdded = new DateTime(2025, 5, 30, 5, 11, 21, 913, DateTimeKind.Utc).AddTicks(5309),
                            DisposalTips = "Remova a espiral metálica se possível (descarte com metais). As folhas de papel limpas vão para o cesto azul.",
                            LastUpdated = new DateTime(2025, 5, 30, 5, 11, 21, 913, DateTimeKind.Utc).AddTicks(5310),
                            Material = "Papel e Metal (espiral)",
                            ProductName = "Caderno Espiral",
                            RecyclingInfo = "Folhas de papel são recicláveis. A espiral metálica também.",
                            SustainabilityImpact = "Contribui para a preservação de árvores."
                        });
                });

            modelBuilder.Entity("BackEnd.Models.Suggestion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Barcode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateSubmitted")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisposalTips")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Material")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RecyclingInfo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SustainabilityImpact")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Barcode");

                    b.ToTable("Suggestions");
                });
#pragma warning restore 612, 618
        }
    }
}
